Heysoft\MenuBundle\Entity\Carrito:
    type: entity
    table: null
    repositoryClass: Heysoft\MenuBundle\Repository\CarritoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        user:
            targetEntity: User
            mappedBy: carrito 
    manyToMany:
        platillos:
            targetEntity: Platillo
            inversedBy: carritos
            joinTable:
                name: carritos_platillos
                joinColumns:
                    carrito_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    platillos_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
