Heysoft\MenuBundle\Entity\Platillo:
    type: entity
    table: null
    repositoryClass: Heysoft\MenuBundle\Repository\PlatilloRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        platillo:
            type: string
            length: 255
            unique: true
        precio:
            type: float
        status:
            type: boolean
        duracion:
            type: integer
        ingredientes:
            type: text
        imagen:
            type: string
            length: 255
            nullable: true
    manyToOne:
        categoria:
            targetEntity: Categoria
            inversedBy: platillos
            joinColumn:
                name: categoria
                referencedColumnName: id
    oneToMany:
        descripciones:
            targetEntity: DescripcionPedido
            mappedBy: platillo 
    lifecycleCallbacks: {  }
