Heysoft\MenuBundle\Entity\PlatilloEntrada:
    type: entity
    table: null
    repositoryClass: Heysoft\MenuBundle\Repository\PlatilloEntradaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        platilloentrada:
            type: string
            length: 255
            unique: true
        precio:
            type: float
    manyToMany:
        platillos:
            targetEntity: Platillo
            mappedBy: platillosentradas
    lifecycleCallbacks: {  }
