<?php

namespace Heysoft\MenuBundle\Repository;

/**
 * PlatilloChicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatilloChicoRepository extends \Doctrine\ORM\EntityRepository
{
}
