<?php

namespace Heysoft\MenuBundle\Repository;

/**
 * PlatilloEntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatilloEntradaRepository extends \Doctrine\ORM\EntityRepository
{
}
