<?php

namespace Heysoft\MenuBundle\Repository;

/**
 * PlatilloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatilloRepository extends \Doctrine\ORM\EntityRepository
{
}
