<?php

namespace Heysoft\MenuBundle\Repository;

/**
 * BebidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BebidaRepository extends \Doctrine\ORM\EntityRepository
{
}
