<?php

namespace Heysoft\MenuBundle\Repository;

/**
 * DescripcionPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescripcionPedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
